import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {C_IDENTITIES,NORMALIZATION_TOPICS,validatePack,calculateUnderwriting,formUnderwriting,researchRoute} from '../lib/challenger-underwriting.js';
import {ASSESSMENTS} from '../lib/challenger-model.js';
import {appendLane,verifyLanes,readLane,lanePath} from '../scripts/challenger-lane-store.mjs';
import {freezeC,debateC} from '../scripts/challenger-c.mjs';
import {compareC} from '../scripts/challenger-underwriting-records.mjs';
const cutoff='2026-09-04T12:00:00Z';
function pack(ticker='CLS'){
 const i=C_IDENTITIES[ticker],periodStart='2026-01-01',periodEnd='2026-06-30';
 const sources=['ANNUAL','QUARTERLY','ISSUER','MARKET'].map((kind,n)=>({id:kind,kind,url:n<2?`https://www.sec.gov/Archives/edgar/data/${i.cik}/fixture.htm`:n===2?`https://${i.host}/fixture`:`https://www.nasdaq.com/market-activity/stocks/${ticker.toLowerCase()}`,publishedAt:n===3?'2026-09-03T20:00:00Z':'2026-08-01T12:00:00Z',observedAt:cutoff,periodEnd:n===3?'2026-09-03':periodEnd,locator:'Synthetic fixture',method:'PUBLIC_SOURCE_REVIEW',precision:'INSTANT'}));
 const facts=[['cfo','CFO',100],['capex','CAPEX',20],['shares','DILUTED_SHARES',10],['sbc','SBC',5],['cash','CASH',30],['debt','DEBT',40],['outstanding','OUTSTANDING_SHARES',12],['price','PRICE',25]].map(([id,metric,value])=>({id,metric,value,sourceId:metric==='PRICE'?'MARKET':'QUARTERLY',locator:'Synthetic table',fact:'Synthetic '+id,unit:metric.includes('SHARES')?'SHARES_M':metric==='PRICE'?'USD_PER_SHARE':'USD_M',periodStart:metric==='PRICE'?'2026-09-03':periodStart,periodEnd:metric==='PRICE'?'2026-09-03':periodEnd,basis:metric==='DILUTED_SHARES'?'DILUTED_WEIGHTED_AVERAGE':metric==='OUTSTANDING_SHARES'?'OUTSTANDING_ALL_CLASSES':metric==='PRICE'?'MARKET_QUOTE':'REPORTED'}));
 return {schemaVersion:'argus.underwriting-pack/1',id:'pack-'+ticker,timestamp:cutoff,evidenceCutoff:cutoff,ticker,company:'Synthetic '+ticker,lane:i.lane,classification:i.lane==='EXTERNAL_DISCOVERY'?'EXTERNAL_CANDIDATE':'CORE_MEMBER',candidateHash:i.lane==='EXTERNAL_DISCOVERY'?'a'.repeat(64):'UNKNOWN',sources,facts,gaps:[]};
}
const support=()=>({value:'Synthetic reviewed assessment',evidenceRefs:['cfo','sbc']});
function draft(ticker='CLS'){return{ticker,independentState:'NEW_OPPORTUNITY',recipe:{cfo:'cfo',capex:'capex',shares:'shares',normalization:{adjustments:[{factId:'sbc',sign:-1,rationale:'Treat recurring compensation as owner cost.'}],review:Object.fromEntries(NORMALIZATION_TOPICS.map(k=>[k,support()]))},valuation:{price:'price',shares:'outstanding',cash:'cash',debt:'debt',shareBridge:support()}},assessments:Object.fromEntries(ASSESSMENTS.map(k=>[k,support()])),evidenceFor:['cfo'],evidenceAgainst:['sbc'],nextResearch:[{kind:'RESEARCH',question:'Review onboarding independently.'}]};}
const form=(p=pack(),d=draft())=>formUnderwriting(p,d,{id:'independent',timestamp:cutoff,packHash:'b'.repeat(64)});
test('C: cash flow, SBC adjustment and diluted FCF/share are traceable and never annualized',()=>{const p=form();assert.equal(p.calculations.reported.fcf,80);assert.equal(p.calculations.reported.fcfPerShare,8);assert.equal(p.calculations.normalized.fcf,75);assert.equal(p.calculations.normalized.fcfPerShare,7.5);assert.deepEqual(p.calculations.normalized.evidenceRefs,['cfo','capex','shares','sbc']);});
test('C: valuation uses outstanding shares, not the diluted period denominator',()=>{const p=form();assert.equal(p.calculations.valuation.equityValueUSDm,300);assert.equal(p.calculations.valuation.enterpriseValueUSDm,310);});
test('C: SBC sensitivity stays explicitly separate from normalized earnings',()=>{const d=draft();d.recipe.normalization='UNKNOWN';d.independentState='UNKNOWN';const p=form(pack(),d);assert.equal(p.calculations.sbcChargedSensitivity.fcfPerShare,7.5);assert.equal(p.calculations.sbcChargedSensitivity.status,'SENSITIVITY_ONLY_NOT_NORMALIZED');assert.equal(p.calculations.normalized,'UNKNOWN');});
for(const field of ['publishedAt','observedAt'])test(`C: future ${field} cannot enter PIT pack`,()=>{const p=pack();p.sources[0][field]='2026-09-05T00:00:00Z';assert.throws(()=>validatePack(p),/PIT/);});
test('C: stale market price cannot support valuation',()=>{const p=pack();p.sources[3].publishedAt='2026-09-02T20:00:00Z';p.facts.find(f=>f.id==='price').periodStart='2026-09-02';p.facts.find(f=>f.id==='price').periodEnd='2026-09-02';p.sources[3].periodEnd='2026-09-02';assert.throws(()=>form(p),/VALUATION_PIT/);});
test('C: date-only price and historical offering prices are not market quotes',()=>{const p=pack();p.sources[3].precision='DAY_END_BOUND';assert.throws(()=>form(p));const q=pack();q.facts.at(-1).basis='OFFERING_PRICE';assert.throws(()=>form(q),/BASIS/);});
test('C: price observation date cannot be relabeled as an earlier valuation date',()=>{const p=pack();p.facts.at(-1).periodStart='2026-06-30';p.facts.at(-1).periodEnd='2026-06-30';assert.throws(()=>form(p),/PRICE_DATE/);});
test('C: annual and quarterly period mixing is rejected',()=>{const p=pack();p.facts.find(f=>f.id==='shares').periodStart='2026-04-01';assert.throws(()=>form(p),/PERIOD_MISMATCH/);});
test('C: basic shares cannot masquerade as diluted shares',()=>{const p=pack();p.facts.find(f=>f.id==='shares').basis='BASIC';assert.throws(()=>form(p),/BASIS/);});
test('C: zero shares, nonfinite numbers and wrong units fail closed',()=>{for(const change of [{value:0},{value:NaN},{unit:'USD_M'}]){const p=pack();Object.assign(p.facts.find(f=>f.id==='shares'),change);assert.throws(()=>form(p));}});
test('C: finite inputs cannot overflow into an infinite valuation',()=>{const p=pack();p.facts.find(f=>f.id==='price').value=1e308;assert.throws(()=>form(p),/OVERFLOW/);});
test('C: unsupported or duplicated normalization adjustments are rejected',()=>{for(const id of ['invented','cfo']){const d=draft();d.recipe.normalization.adjustments[0].factId=id;assert.throws(()=>form(pack(),d));}const d=draft();d.recipe.normalization.adjustments.push(d.recipe.normalization.adjustments[0]);assert.throws(()=>form(pack(),d));});
for(const topic of NORMALIZATION_TOPICS)test(`C: missing ${topic} review cannot become normalized owner earnings`,()=>{const d=draft();d.recipe.normalization.review[topic]='UNKNOWN';assert.throws(()=>form(pack(),d),/NORMALIZATION/);});
test('C: missing valuation blocks every substantive stance',()=>{for(const state of ['NEW_OPPORTUNITY','CONTRARIAN_TRAP']){const d=draft();d.independentState=state;d.recipe.valuation='UNKNOWN';assert.throws(()=>form(pack(),d),/INSUFFICIENT/);}});
test('C: reported FCF is not automatically normalized',()=>{const d=draft();d.recipe.normalization='UNKNOWN';assert.throws(()=>form(pack(),d),/INSUFFICIENT/);d.independentState='UNKNOWN';assert.equal(form(pack(),d).calculations.normalized,'UNKNOWN');});
for(const state of ['BUY','SELL','TRIM','ADD','SUPPORT_CORE','CHALLENGE_CORE','FAVORABLE'])test(`C: external ${state} forbidden`,()=>{const d=draft();d.independentState=state;assert.throws(()=>form(pack(),d),/ACTION_OR_ANCHOR/);});
test('C: opportunity means reviewed research, never automatic onboarding',()=>{const p=form(),r=researchRoute(p);assert.equal(r.queue,'ZERO_BASED_ONBOARDING_RESEARCH');assert.equal(r.canAuthorizePortfolioAction,false);assert.equal(r.requiresReviewedOnboarding,true);});
test('C: missing source documents, counterevidence or falsification fail closed',()=>{for(const kind of ['ANNUAL','ISSUER']){const p=pack();p.sources=p.sources.filter(s=>s.kind!==kind);assert.throws(()=>form(p),/INSUFFICIENT/);}for(const field of ['evidenceFor','evidenceAgainst']){const d=draft();d[field]=[];assert.throws(()=>form(pack(),d),/INSUFFICIENT/);}const d=draft();d.assessments.falsificationConditions='UNKNOWN';assert.throws(()=>form(pack(),d),/INSUFFICIENT/);});
test('C: source CIK/issuer identity and extra Core narrative fields are denied',()=>{for(const url of ['https://www.sec.gov/Archives/edgar/data/999/fixture.htm','http://localhost/a','https://evil.example/a']){const p=pack();p.sources[0].url=url;assert.throws(()=>form(p));}assert.throws(()=>validatePack({...pack(),coreNarrative:'Anchoring'}));});
test('C: no expansion beyond eight companies or lane relabeling',()=>{assert.throws(()=>validatePack({...pack(),ticker:'NEWCO'}));assert.throws(()=>validatePack({...pack(),lane:'CORE_CHALLENGE'}));});
function temp(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'argus-c-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'datasets'));fs.mkdirSync(path.join(root,'observer'));fs.writeFileSync(path.join(root,'datasets/universe_v10_33.js'),'export const UNIVERSE = deepFreeze('+JSON.stringify({'Company Universe':Object.entries(C_IDENTITIES).filter(([,i])=>i.lane==='CORE_CHALLENGE').map(([ticker])=>({Ticker:ticker,Company:'Synthetic '+ticker}))})+');');fs.writeFileSync(path.join(root,'observer/events.jsonl'),'protected');const git=args=>execFileSync('git',args,{cwd:root,stdio:'pipe'});git(['init','--quiet']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=f@example.invalid','commit','--quiet','-m','Anchor']);return root;}
function seed(root){const hashes=[],drafts=[];for(const ticker of Object.keys(C_IDENTITIES)){const p=pack(ticker);if(p.lane==='EXTERNAL_DISCOVERY'){const i=C_IDENTITIES[ticker];const c=appendLane(root,'discovery/candidates.jsonl',{schemaVersion:'argus.external-candidate/1',id:'candidate-'+ticker,timestamp:cutoff,ticker,company:p.company,classification:'EXTERNAL_CANDIDATE',cik:i.cik.padStart(10,'0'),issuerHosts:[i.host],identitySources:[{url:p.sources[0].url,locator:'Fixture',observedAt:cutoff},{url:p.sources[2].url,locator:'Fixture',observedAt:cutoff}]});p.candidateHash=c.hash;}hashes.push(appendLane(root,'underwriting/packs.jsonl',p).hash);drafts.push(draft(ticker));}return {hashes,drafts};}
test('C: complete eight-company batch freezes before Core access and cannot mutate protected files',t=>{const root=temp(t),before=fs.readFileSync(path.join(root,'datasets/universe_v10_33.js')),s=seed(root);freezeC(root,s.hashes,s.drafts,'fixture');assert.equal(verifyLanes(root)[6].length,8);assert.ok(fs.readFileSync(path.join(root,'datasets/universe_v10_33.js')).equals(before));assert.equal(fs.readFileSync(path.join(root,'observer/events.jsonl'),'utf8'),'protected');});
test('C: debate cannot read Core before complete frozen batch',async t=>{const root=temp(t);await assert.rejects(()=>debateC(root,'absent'),/FROZEN_BATCH/);assert.throws(()=>freezeC(root,[],[],'empty'),/BATCH_SCOPE/);});
test('C: direct packets without source pack and modified calculations cannot append',t=>{const root=temp(t);assert.throws(()=>appendLane(root,'underwriting/packets.jsonl',form()),/REPLAY/);const s=seed(root),p=pack('FIS');const forged=formUnderwriting(p,draft('FIS'),{id:'f',timestamp:cutoff,packHash:s.hashes[0]});const q=structuredClone(forged);q.calculations.reported.fcf=999;assert.throws(()=>appendLane(root,'underwriting/packets.jsonl',q),/REPLAY/);});
test('C: whole journal truncation and edits detected with trusted anchor',t=>{const root=temp(t);seed(root);const file=lanePath(root,'underwriting/packs.jsonl'),anchor=fs.readFileSync(file);fs.writeFileSync(file,'');assert.throws(()=>readLane(root,'underwriting/packs.jsonl',anchor),/APPEND_ONLY/);fs.writeFileSync(file,anchor.toString().replace('Synthetic','Tampered'));assert.throws(()=>readLane(root,'underwriting/packs.jsonl',''),/CHAIN/);});
test('C: external packet cannot enter Core namespace or protected destinations',t=>{const root=temp(t);assert.throws(()=>appendLane(root,'core/coverage.jsonl',form()));for(const file of ['../datasets/universe_v10_33.js','../observer/events.jsonl','../lib/engine_v10_25.js'])assert.throws(()=>lanePath(root,file));});
test('C: admitted ARGUS prices replay exact immutable source value, dates and fingerprint',t=>{const root=temp(t),raw="const timestamp='2026-09-03T20:00:00Z'; verifiedAt:'2026-09-04T12:00:00Z'; FIS:quote(25,'https://stockanalysis.com/stocks/fis/')";fs.writeFileSync(path.join(root,'datasets/market_snapshot.js'),raw);const p=pack('FIS');Object.assign(p.sources[3],{kind:'VERIFIED_PRICE',method:'ARGUS_VERIFIED_SNAPSHOT',url:'https://stockanalysis.com/stocks/fis/',locator:'sha256:'+createHash('sha256').update(raw).digest('hex')});appendLane(root,'underwriting/packs.jsonl',p);for(const change of ['value','hash','date']){const q=structuredClone(p);q.id=change;if(change==='value')q.facts.at(-1).value=26;else if(change==='hash')q.sources[3].locator='sha256:'+'0'.repeat(64);else q.sources[3].observedAt='2026-09-04T11:00:00Z';assert.throws(()=>appendLane(root,'underwriting/packs.jsonl',q),/QUOTE_REPLAY/);}assert.equal(fs.readFileSync(path.join(root,'datasets/market_snapshot.js'),'utf8'),raw);});
test('C: high disagreement remains reunderwrite only and requires post-freeze read',()=>{const p=pack('FIS'),d=draft('FIS');d.independentState='UNFAVORABLE';const packet=form(p,d);const c={ticker:'FIS',state:'Fixture',narrative:'Fixture',economicDirection:'FAVORABLE',ref:'Fixture',contentHash:'c'.repeat(64),asOf:cutoff,availableAt:cutoff,readAt:cutoff};const result=compareC(packet,c,cutoff);assert.equal(result.state,'CHALLENGE_CORE');assert.equal(result.researchPriority.kind,'REUNDERWRITE');assert.equal(result.canAuthorizePortfolioAction,false);assert.throws(()=>compareC(packet,c,'2026-09-04T13:00:00Z'),/BEFORE_FREEZE/);});
