import {language} from './view.js';
const dictionary={
'Skip to dashboard':'דלג ללוח','Workspace':'סביבת עבודה','WORKSPACE':'סביבת עבודה','Main navigation':'ניווט ראשי','THE ARGUS PRINCIPLE':'עקרון ARGUS','A great company.':'חברה מצוינת.','A separate allocation decision.':'החלטת הקצאה נפרדת.','V10.25 baseline locked':'בסיס V10.25 נעול','Portfolio overlay · V10.34':'שכבת תיק · V10.34',
'Portfolio overview':'סקירת התיק','Decision board':'לוח החלטות','Company research':'מחקר חברות','Portfolio construction':'בניית תיק','AI infrastructure':'תשתיות AI','Forward proof':'הוכחה קדימה','Your portfolio. In perspective.':'התיק שלך. בפרספקטיבה.','Main Decision Board':'לוח ההחלטות הראשי','Portfolio Construction Overlay':'שכבת בניית התיק','AI Infrastructure Event Radar':'רדאר אירועי תשתיות AI','Forward Proof / System Status':'הוכחה קדימה / מצב המערכת',
'RESEARCH → DECISION → ALLOCATION':'מחקר ← החלטה ← הקצאה','Conviction at the company level. Discipline at the portfolio level.':'ביטחון ברמת החברה. משמעת ברמת התיק.','Price refresh required':'נדרש עדכון מחיר','Refresh required':'נדרש עדכון מחיר','refresh required':'נדרש עדכון מחיר','PORTFOLIO SUMMARY':'סיכום התיק','Supplied portfolio · partial holdings':'תיק שסופק · אחזקות חלקיות','Portfolio size':'גודל התיק','Supplied total · not a live NAV':'סכום שסופק · אינו NAV חי','INTU holding value':'שווי אחזקת INTU','INTU concentration':'ריכוז INTU','EST.':'אומדן','OVER MAX':'מעל התקרה','INTU remaining add capacity':'קיבולת הוספה ל־INTU','BLOCKED':'חסום','Portfolio decision · DO NOT ADD':'החלטת תיק · לא להוסיף','Target 6–8% · hard maximum 12%':'יעד 6–8% · תקרה קשיחה 12%','Concentration alert: INTU exceeds its hard maximum.':'התראת ריכוזיות: INTU חורגת מהתקרה הקשיחה.','Review exposure':'בדוק חשיפה',
'Company':'חברה','Live price':'מחיר חי','Lock price':'מחיר נעילה','Intrinsic value':'שווי פנימי','Intrinsic value range':'טווח שווי פנימי','Expected IV':'שווי צפוי','Score':'ציון','Company decision':'החלטת חברה','Portfolio decision':'החלטת תיק','Research':'מחקר','Current weight':'משקל נוכחי','Target':'יעד','Hard max':'תקרה קשיחה','Add capacity':'קיבולת הוספה','Not supplied':'לא סופק','Not set':'לא הוגדר','Unassessed':'לא נבחן','NO ACTION':'ללא פעולה','DO NOT ADD':'לא להוסיף','BUY':'קנייה · BUY','WAIT':'להמתין · WAIT','WATCH':'מעקב · WATCH','PROVE IT':'נדרשת הוכחה','Overview':'סקירה','Why Buy':'למה לקנות','Why Not':'למה לא','Forecast':'תחזית','Holdings':'אחזקות','Decision Engine':'מנוע החלטה','All companies':'כל החברות','Buy':'קנייה','Wait':'להמתין','Prove it':'נדרשת הוכחה','Watch':'מעקב','Find a company…':'חפש חברה…','Find a company':'חפש חברה','Filter company research':'סינון מחקר חברות','Select a panel to explore the thesis':'בחר חלונית לבחינת התזה',
'01 / THE DECISION LAYER':'01 / שכבת ההחלטה','02 / UNDER THE SURFACE':'02 / מתחת לפני השטח','03 / CAPITAL HAS CONSTRAINTS':'03 / להון יש מגבלות','04 / SIGNALS, NOT ORDERS':'04 / אותות מחקר','05 / EVIDENCE BEFORE AUTHORIZATION':'05 / ראיות לפני הרשאה','◈ V10.25 LOCKED BASELINE':'◈ בסיס V10.25 נעול','Four locked decisions. One portfolio constraint.':'ארבע החלטות נעולות. מגבלת תיק אחת.','Live prices:':'מחירים חיים:','Portfolio decisions are a separate overlay.':'החלטות תיק הן שכבה נפרדת.','◈ Locked values are historical research inputs, not current quotes.':'◈ ערכים נעולים הם נתוני מחקר היסטוריים, לא ציטוטים נוכחיים.',
'V10.34 · SEPARATE FROM BASELINE':'V10.34 · נפרד מהבסיס','Company BUY does not automatically mean Portfolio BUY.':'החלטת קנייה לחברה אינה החלטת קנייה לתיק.','Position size, sector exposure, and shared economic risks have the final say.':'גודל הפוזיציה, חשיפה סקטוריאלית וסיכונים כלכליים משותפים קובעים את ההקצאה.','INTU allocation guardrails':'מגבלות הקצאת INTU','RED · OVER MAX':'אדום · מעל התקרה','Estimate using':'בסיס האומדן','Locked price · $359.30':'מחיר נעול · $359.30','Average cost · $357.21283':'עלות ממוצעת · $357.21283','Estimated current weight':'אומדן המשקל הנוכחי','Live weight requires a verified price':'משקל חי דורש מחיר מאומת','Target allocation':'הקצאת יעד','Hard maximum':'תקרה קשיחה','Above hard max · est.':'מעל התקרה · אומדן','Remaining add capacity':'קיבולת הוספה שנותרה','NO ADD':'אין להוסיף','Portfolio visibility':'תמונת התיק','PARTIAL HOLDINGS':'אחזקות חלקיות','Known holding · estimate':'אחזקה ידועה · אומדן','Unclassified remainder':'יתרה לא מסווגת','Not assumed to be cash':'אינה נחשבת למזומן','Other holdings have not been supplied. Sector totals, correlated exposure, and total portfolio P/L remain incomplete.':'יתר האחזקות לא סופקו. חשיפה ענפית, סיכונים מתואמים ורווח/הפסד כולל אינם מלאים.','Economic Risk Bucket':'דלי סיכון כלכלי','CONCENTRATED':'ריכוזי','Sector / Risk Bucket exposure':'חשיפה לסקטור / דלי סיכון','Known exposure · est.':'חשיפה ידועה · אומדן','Concentration status':'מצב ריכוזיות','RED · ABOVE HARD MAX':'אדום · מעל התקרה','ORANGE · INCOMPLETE':'כתום · מידע חלקי',
'SHADOW RESEARCH':'מחקר צל','Demand proof':'הוכחת ביקוש','Owner economics':'כלכלת הבעלים','Valuation':'הערכת שווי','Concentration':'ריכוזיות','Normalized cash conversion':'המרת מזומן מנורמלת','Scope':'היקף','Earnings':'דוחות כספיים','Guidance':'תחזית הנהלה','Capital allocation':'הקצאת הון','Debt':'חוב','Regulatory / geopolitical':'רגולציה / גאופוליטיקה','Price dislocation + evidence':'שינוי מחיר חריג + ראיות',
'AUTHORIZATION BLOCKED':'הרשאה חסומה','The baseline stays locked.':'הבסיס נשאר נעול.','The evidence moves forward.':'הראיות מתקדמות.','Historical decisions are preserved. Portfolio overlays and new research never rewrite the forward test.':'החלטות היסטוריות נשמרות. שכבות תיק ומחקר חדש אינן משכתבות את המבחן העתידי.','Raw forward locks':'נעילות עתידיות גולמיות','Correlation-adjusted N':'N מתוקן למתאם','Resolved / minimum gate':'מוכרע / סף מינימלי','Resolved forward evidence':'ראיות עתידיות שהוכרעו','First 6M checkpoint':'נקודת בדיקה ראשונה — 6 חודשים','Required proof score':'ציון הוכחה נדרש','Live market feed':'הזנת שוק חיה','Not connected':'לא מחובר','Data & methodology ↗':'נתונים ומתודולוגיה ↗','Close panel':'סגור חלונית',
'Capacity = max(0, hard maximum − position value), subject to company, sector, and risk gates. Capacity is a ceiling, not an instruction to buy.':'קיבולת = max(0, תקרה קשיחה − שווי פוזיציה), בכפוף לתנאי חברה, סקטור וסיכון. הקיבולת היא תקרה, לא הוראת קנייה.',
'One shared AI-capex cycle. Three distinct evidence gates. Prior research status; new events require verification.':'מחזור השקעות AI משותף. תנאי ראיות נפרדים. מחקר קודם; אירועים חדשים דורשים אימות.',
'Imported prior ARGUS proof snapshot (03 Sep 2026), not a live counter. Historical diagnostic results do not substitute for clean forward outcomes. No trading or API execution is enabled.':'תצלום הוכחה מיובא מ־3 בספטמבר 2026, לא מונה חי. תוצאות אבחון היסטורי אינן מחליפות תוצאות עתידיות נקיות. אין ביצוע מסחר או API.',
'No companies match this view. Clear your search or select All companies.':'אין חברות המתאימות לתצוגה. נקה את החיפוש או בחר את כל החברות.'
};
export function translateDOM(root=document.body){
 if(language!=='he')return;
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 while(node=walker.nextNode()){if(node.parentElement.closest('script,style,.source-value'))continue;const key=node.nodeValue.trim();if(dictionary[key])node.nodeValue=node.nodeValue.replace(key,dictionary[key]);}
 for(const el of root.querySelectorAll('[aria-label],[placeholder]'))for(const a of ['aria-label','placeholder']){const x=el.getAttribute(a);if(dictionary[x])el.setAttribute(a,dictionary[x]);}
}
