import {MONITORS} from './observer-config.js';
import {parseJournal,openObserverReviews,observerHealth,scanSystemFailure} from './observer-model.js';
import * as V from './view.js';
let evidence=[],scans=[],workflow='unknown',loadError='';
const $=s=>document.querySelector(s),tr=(en,he)=>V.t(en,he);
const actionsURL='https://github.com/zachor-sketch/argus-dashboard/actions/workflows/observer.yml';
function reviews(){try{const rows=JSON.parse(localStorage.getItem('ARGUS_OBSERVER_REVIEWS')||'[]');return Array.isArray(rows)?rows:[]}catch{return []}}
export const observerOpen=()=>openObserverReviews(evidence,reviews());
function eventHTML(e){return `<details class="observer-event"><summary><bdi>${V.esc(e.ticker)}</bdi> · ${V.esc(e.eventType)} · ${V.date(e.timestamp)} · ${V.esc(e.materiality)}</summary>${V.stats([[tr('Source authority','סמכות מקור'),V.esc(e.sourceAuthorityTier)],[tr('Affected variable','משתנה כלכלי מושפע'),V.esc(e.variable)],[tr('Likely direction','כיוון אפשרי'),tr('Ambiguous — review required','לא חד־משמעי — נדרשת בדיקה')],[tr('Detected at','זוהה במועד'),V.date(e.detectedAt,true)]])}<blockquote dir="auto">${V.esc(e.rawFact)}</blockquote><p>${V.link(e.source,tr('Original source','מקור מקורי'))}</p><p class="muted">${tr('Deterministic excerpt or filing notice. Not an established valuation change or investment decision.','קטע מקור או הודעת דיווח שזוהו לפי כללים. אין כאן שינוי שווי מוכח או החלטת השקעה.')}</p>${e.reviewRequired&&!reviews().some(r=>r.eventId===e.id)?`<form data-observer-review="${e.id}"><label>${tr('Human review note','הערת בדיקה אנושית')}<input name="note" required minlength="12"></label><button>${tr('Record reviewed locally','תעד בדיקה מקומית')}</button></form>`:''}</details>`}
function render(){
 const scan=scans.at(-1),open=observerOpen(),now=Date.now(),failed=scan?.failedSources||[],today=new Date().toISOString().slice(0,10),health=c=>observerHealth(c,scan,open,now,workflow),stale=MONITORS.filter(c=>health(c)==='red');
 const host=$('#observer');if(!host)return;
 const systemFailure=workflow==='failed'||scanSystemFailure(scan),partial=scan?.status==='PARTIAL'&&!systemFailure;
 const failureMessage=scanSystemFailure(scan)?tr('SYSTEM FAILURE: no complete company coverage or a global regulatory connector failure. Partial IR evidence does not restore SEC coverage.','כשל מערכת: אין כיסוי מלא לחברות או שקיים כשל רוחבי במקור רגולטורי. ראיות חלקיות מאתרי קשרי משקיעים אינן משחזרות כיסוי SEC.'):'';
 host.innerHTML=`<div class="section-heading"><div><div class="eyebrow">ARGUS OBSERVER V1</div><h2>${tr('Fundamentals observer','משקיף על יסודות העסק')}</h2></div>${V.pill(systemFailure?tr('SYSTEM FAILURE','כשל מערכת'):partial?tr('SYSTEM HEALTH · PARTIAL','בריאות מערכת · כיסוי חלקי'):scan?.status==='SUCCESS'&&workflow==='success'?tr('SCAN COMPLETE','הסריקה הושלמה'):tr('COVERAGE UNCONFIRMED / PARTIAL','כיסוי חלקי / לא מאומת'),systemFailure?'negative':'caution')}</div>
 <div class="construction-rule"><strong>${tr('Evidence → human review. Never an automatic decision.','ראיות ← בדיקה אנושית. לעולם לא החלטה אוטומטית.')}</strong><span>${tr('Daily at 06:17 UTC. No prices, paid AI, brokerage or trading. Schedule delays and missed runs become stale after 36 hours.','מדי יום ב־06:17 UTC. ללא מחירים, AI בתשלום, ברוקר או מסחר. עיכוב או החמצת סריקה מסומנים כנתונים מיושנים לאחר 36 שעות.')}</span></div>
 <p class="observer-warning" role="status">${failureMessage?V.esc(failureMessage):loadError?V.esc(loadError):workflow==='failed'?tr('Latest GitHub Actions run failed. Inspect the run; prior successful data does not prove current coverage.','הריצה האחרונה ב־GitHub Actions נכשלה. יש לבדוק אותה; נתונים קודמים אינם מוכיחים כיסוי עדכני.'):workflow==='unknown'?tr('Workflow status could not be verified. No company is marked green.','לא ניתן לאמת את מצב התהליך. אף חברה אינה מסומנת בירוק.'):workflow==='running'?tr('Observer workflow is running; final coverage is not confirmed.','תהליך המשקיף פועל; הכיסוי הסופי עדיין לא אומת.'):partial?tr('Partial coverage: the observer ran, but source gaps remain. Incomplete companies stay red; inspect the source failures below.','כיסוי חלקי: המשקיף פעל, אך נותרו פערי מקורות. חברות עם ראיות חסרות נשארות אדומות; פירוט הכשלים מופיע למטה.'):tr('Source availability is separate from human review. Red includes overdue reviews, failed sources and new material evidence.','זמינות מקורות נפרדת מבדיקה אנושית. אדום כולל בדיקות באיחור, מקורות שנכשלו וראיות מהותיות חדשות.')}</p>
 <p class="observer-scan-result">${tr('Latest completed scan','הסריקה האחרונה שהסתיימה')}: ${V.date(scan?.finishedAt,true)} · ${tr('Usable company sources','מקורות חברה שמישים')}: ${scan?.usableCompanies??'—'}/${MONITORS.length} · ${tr('Minimum usable coverage','כיסוי שמיש מזערי')}: ${scan?.minimumUsableCompanies??20}/${MONITORS.length}</p>
 <p class="observer-regulatory-status">${tr('SEC successful companies','חברות עם כיסוי SEC מוצלח')}: ${scan?.secSuccessfulCompanies??'—'} / ${scan?.secApplicableCompanies??'—'} · ${tr('Regulatory connector','חיבור למקור רגולטורי')}: <bdi>${V.esc(scan?.secConnectorStatus||'UNCONFIRMED')}</bdi> · <bdi>${V.esc((scan?.reasonCodes||[]).join(' · '))}</bdi></p>
 <p>${V.link(actionsURL,tr('Workflow runs / failures / manual run','ריצות / תקלות / הפעלה ידנית'))}</p>
 <div class="observer-metrics">${[[tr('Universe configured','חברות שהוגדרו'),100],[tr('Companies scanned successfully','חברות שנסרקו בהצלחה'),scan?.companies?.filter(c=>c.ok).length||0],[tr('Last fully successful scan','סריקה מלאה מוצלחת אחרונה'),V.date(scan?.lastSuccessfulScan,true)],[tr('New evidence today (UTC)','ראיות חדשות היום (UTC)'),evidence.filter(e=>e.detectedAt.startsWith(today)).length],[tr('High-materiality events','אירועים מהותיים'),evidence.filter(e=>e.materiality==='high').length],[tr('Open reviews','בדיקות פתוחות'),open.length],[tr('Failed sources','מקורות שנכשלו'),failed.length],[tr('Stale / review-required companies','חברות מיושנות / דורשות בדיקה'),stale.length]].map(([k,v])=>`<article class="panel"><small>${k}</small><strong>${v}</strong></article>`).join('')}</div>
 <div class="panel form-panel"><label>${tr('Search monitoring profiles','חיפוש בפרופילי הניטור')}<input id="observer-search" type="search"></label><div class="table-scroll"><table><thead><tr>${[tr('Company','חברה'),tr('Coverage / review state','כיסוי / מצב בדיקה'),tr('Last successful source scan','סריקת מקור מוצלחת אחרונה'),tr('Last review / due','בדיקה אחרונה / מועד הבא'),tr('Company-specific sensors','חיישנים ייחודיים לחברה')].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${MONITORS.map(c=>{const r=scan?.companies?.find(r=>r.ticker===c.ticker),state=health(c);return `<tr><td><bdi>${V.esc(c.ticker)}</bdi><small>${V.esc(c.company)}</small></td><td><span class="observer-state ${state}">● ${tr(state==='green'?'Current':state==='orange'?'Approaching / unconfirmed':'Review required',state==='green'?'עדכני':state==='orange'?'מתקרב / לא מאומת':'נדרשת בדיקה')}</span><small><bdi>${V.esc(r?.coverage||'NOT_SCANNED')}</bdi></small></td><td>${V.date(r?.lastSuccessfulScan,true)}</td><td>${V.date(c.lastReview)} / ${V.date(c.reviewDue)}</td><td><details><summary>${tr('Sensors and source routes','חיישנים ונתיבי מקור')}</summary><p dir="auto">${V.esc(c.engine)}</p><p dir="auto">${V.esc(c.sensors)}</p>${V.link(c.ir,tr('Authoritative issuer route','נתיב מנפיק מהמקור'))}<p>${tr('Review dates are the source research schedule; scans never reset them.','מועדי הבדיקה מקורם במחקר; סריקה אינה מאפסת אותם.')}</p></details></td></tr>`}).join('')}</tbody></table></div></div>
 <details class="panel form-panel"><summary>${tr('Failed sources and coverage gaps','מקורות שנכשלו ופערי כיסוי')} (${failed.length})</summary>${failed.length?failed.map(f=>`<p><bdi>${V.esc(f.ticker)}</bdi> · <span dir="auto">${V.esc(f.source)} — ${V.esc(f.error)}</span></p>`).join(''):tr('No recorded failures; check scan and workflow status above.','לא נרשמו כשלים; יש לבדוק את מצב הסריקה והתהליך למעלה.')}</details>
 <details class="panel form-panel"><summary>${tr('Latest evidence (up to 100) · full append-only journal','ראיות אחרונות (עד 100) · יומן מלא בהוספה בלבד')}</summary><p><a href="./observer/events.jsonl">${tr('Full evidence journal','יומן הראיות המלא')}</a></p>${evidence.slice(-100).reverse().map(eventHTML).join('')||tr('No detected evidence yet.','טרם זוהו ראיות.')}</details>`;
 $('#observer-search').oninput=e=>document.querySelectorAll('#observer tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase()));
 let queue=$('#observer-queue');if(!queue){queue=document.createElement('article');queue.id='observer-queue';queue.className='panel form-panel';$('#events').append(queue)}
 queue.innerHTML=`<h3>${tr('Observer OPEN reviews','בדיקות OPEN של המשקיף')} · ${open.length}</h3><p>${tr('Local review acknowledgments never change source evidence or investment decisions.','אישור בדיקה מקומי אינו משנה ראיות מקור או החלטות השקעה.')}</p>${open.slice().reverse().map(eventHTML).join('')||tr('No open observer items.','אין פריטי משקיף פתוחים.')}`;
 document.dispatchEvent(new CustomEvent('argus-observer-updated'));
}
export async function bootObserver(){
 const section=document.createElement('section');section.id='observer';$('#proof').before(section);
 $('.sidebar nav').insertAdjacentHTML('beforeend',`<a href="#observer">◇ ${tr('Observer status','מצב המשקיף')}</a>`);render();
 try{const data=await Promise.all(['events','scans'].map(async name=>{const r=await fetch('./observer/'+name+'.jsonl',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return parseJournal(await r.text())}));[evidence,scans]=data}catch{loadError=tr('Observer journals could not be loaded. Coverage is unverified.','לא ניתן לטעון את יומני המשקיף. הכיסוי אינו מאומת.')}
 try{const batches=await Promise.all(['','&event=schedule','&event=workflow_dispatch'].map(async filter=>{const r=await fetch('https://api.github.com/repos/zachor-sketch/argus-dashboard/actions/workflows/observer.yml/runs?per_page=1'+filter,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('STATUS_UNAVAILABLE');return (await r.json()).workflow_runs||[]}));const runs=batches.flat().sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at)),latest=runs[0],run=latest?.status==='completed'&&latest.conclusion!=='success'?latest:runs.find(r=>r.event!=='push')||latest;workflow=!run?'unknown':run.status!=='completed'?'running':run.conclusion==='success'?'success':'failed'}catch{workflow='unknown'}
 render();setInterval(()=>{if(!document.activeElement?.closest('#observer input, #observer-queue input'))render()},60000);
 document.addEventListener('submit',e=>{const form=e.target.closest('[data-observer-review]');if(!form)return;e.preventDefault();const note=new FormData(form).get('note')?.trim();if(!note||note.length<12)return;try{const rows=reviews();rows.push({eventId:form.dataset.observerReview,note,reviewedAt:new Date().toISOString()});localStorage.setItem('ARGUS_OBSERVER_REVIEWS',JSON.stringify(rows));render()}catch{loadError=tr('Local review could not be saved.','לא ניתן לשמור את הבדיקה המקומית.');render()}});
}
