// Operational routing corrections only. Never modifies the imported research universe.
export const SOURCE_ROUTES={
 LLOY:{secTicker:'LYG',secCIK:'0001160106',source:'https://www.lloydsbankinggroup.com/investors/shareholder-information.html',reason:'Issuer identifies LLOY as London ordinary shares and LYG as its NYSE ADR; validate LYG and this CIK with SEC on every scan.'},
 'LUMI.TA':{ir:'https://www.leumi.co.il/en/Investor-Relations',source:'https://www.leumi.co.il/en/Investor-Relations',reason:'Current issuer IR replaces the obsolete english.leumi.co.il 404 route; issuer explicitly states IR is not all regulatory disclosures.'},
 'TRPZ.TA':{ir:'https://www.turpaz.co.il/Investor-announcements',source:'https://www.turpaz.co.il/',reason:'Issuer investor announcements replace a TASE quote page; PDF and regulatory gaps remain incomplete.'},
 'SU.PA':{discoveryURLs:['https://www.se.com/ww/en/about-us/newsroom/news/'],dateOrder:'DMY',headerDate:true,source:'https://www.se.com/ww/en/about-us/newsroom/news/press-releases/Schneider-Electric-reports-strong-first-halfyear-results-under-new-sustainability-roadmap-Impact-2030-6a69ed90e012c8533b0e1db3/',reason:'Inspected issuer template displays 30/07/2026 in the article header; prefer this visible date over unrelated/conflicting embedded attachment/template dates. Selected HTML evidence remains partial.'},
 'SY1.DE':{discoveryURLs:['https://www.symrise.com/newsroom/press-releases/rss.xml'],source:'https://www.symrise.com/newsroom/press-releases/',reason:'Issuer-linked RSS contains individually dated release URLs.'},
 'GIVN.SW':{discoveryURLs:['https://www.givaudan.com/media/media-releases'],source:'https://www.givaudan.com/media/media-releases',reason:'Issuer news index contains individual releases rather than financial navigation pages.'},
 'CRDA.L':{discoveryURLs:['https://www.croda.com/en-gb/media-hub/news'],source:'https://www.croda.com/en-gb/media-hub/news',reason:'Issuer news index links HTML results announcements.'},
 MUV2:{discoveryURLs:['https://www.munichre.com/en/company/investors/reports-and-presentations/results-reports.html'],dateOrder:'MDY',source:'https://www.munichre.com/en/company/media-relations/media-information-and-corporate-news/media-information/2026/half-year-financial-report.html',reason:'Results index links individual media announcements; English issuer release date 08/07/2026 is 7 August, as corroborated by the issuer release PDF.'},
 'MC.PA':{dateOrder:'MDY',source:'https://www.lvmh.com/en/publications/accelerating-growth-in-the-second-quarter---solid-first-half-results',reason:'Issuer explicitly displays Published on 07.27.2026 in month/day/year order.'}
};
